/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as MediaVideoRouteImport } from './routes/media.video'
import { Route as MediaQrRouteImport } from './routes/media.qr'
import { Route as MediaImageRouteImport } from './routes/media.image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaVideoRoute = MediaVideoRouteImport.update({
  id: '/media/video',
  path: '/media/video',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaQrRoute = MediaQrRouteImport.update({
  id: '/media/qr',
  path: '/media/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaImageRoute = MediaImageRouteImport.update({
  id: '/media/image',
  path: '/media/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/media/image': typeof MediaImageRoute
  '/media/qr': typeof MediaQrRoute
  '/media/video': typeof MediaVideoRoute
  '/media/': typeof MediaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/media/image': typeof MediaImageRoute
  '/media/qr': typeof MediaQrRoute
  '/media/video': typeof MediaVideoRoute
  '/media': typeof MediaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/media/image': typeof MediaImageRoute
  '/media/qr': typeof MediaQrRoute
  '/media/video': typeof MediaVideoRoute
  '/media/': typeof MediaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/media/image' | '/media/qr' | '/media/video' | '/media/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/media/image' | '/media/qr' | '/media/video' | '/media'
  id:
    | '__root__'
    | '/'
    | '/media/image'
    | '/media/qr'
    | '/media/video'
    | '/media/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MediaImageRoute: typeof MediaImageRoute
  MediaQrRoute: typeof MediaQrRoute
  MediaVideoRoute: typeof MediaVideoRoute
  MediaIndexRoute: typeof MediaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/video': {
      id: '/media/video'
      path: '/media/video'
      fullPath: '/media/video'
      preLoaderRoute: typeof MediaVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/qr': {
      id: '/media/qr'
      path: '/media/qr'
      fullPath: '/media/qr'
      preLoaderRoute: typeof MediaQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/image': {
      id: '/media/image'
      path: '/media/image'
      fullPath: '/media/image'
      preLoaderRoute: typeof MediaImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MediaImageRoute: MediaImageRoute,
  MediaQrRoute: MediaQrRoute,
  MediaVideoRoute: MediaVideoRoute,
  MediaIndexRoute: MediaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
